language: python
python: 3.10
dist: focal

install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - python3 -m keyring --disable
  - poetry install -E timestamps

script:
  - poetry run pre-commit run --all-files
  - poetry run pytest tests
