name: image-parsing
channels:
  - conda-forge
dependencies:
  - python=3.7
  # dev dependencies
  - sphinx
  - sphinx_rtd_theme
  - pytest
  - pre_commit
  # main dependencies
  - exifread
  - pandas
  - click
  - decorator
  - timezonefinder
  - xmltodict
