name: image-parsing
channels:
  - conda-forge
dependencies:
  - python=3.6
  # dev dependencies
  - sphinx
  - sphinx_rtd_theme
  - m2r
  - pytest
  - pre_commit
  # main dependencies
  - exifread
  - xmltodict
  - pandas
