[tool.poetry]
name = "imgparse"
version = "1.8.0"
description = "Python image-metadata-parser utilities"
authors = []

[tool.poetry.dependencies]
python = "^3.7"
exifread = "*"
pandas = "*"
click = "*"
decorator = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
sphinx_rtd_theme = "*"
sphinx = "*"
pre_commit = "*"

[tool.poetry.scripts]
imgparse = "imgparse.cli:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
