[tool.poetry]
name = "imgparse"
version = "1.12.5.dev2"
description = "Python image-metadata-parser utilities"
authors = []

[tool.poetry.dependencies]
python = "^3.7"
exifread = "*"
click = "*"
decorator = "*"
xmltodict = "*"
requests = "*"

pandas = {version = "*", optional = true}
timezonefinder = {version = "^5.2.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-coverage= "*"
sphinx_rtd_theme = "*"
sphinx = "*"
pre_commit = "*"
requests-mock = "*"

[tool.poetry.scripts]
imgparse = "imgparse.cli:cli"

[tool.poetry.extras]
metadata_csv = ["pandas"]
dji_timestamps = ["timezonefinder"]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["click", "decorator", "exifread", "pandas", "pytest", "pytz", "requests", "xmltodict"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
