[tool.poetry]
name = "imgparse"
version = "1.13.1"
description = "Python image-metadata-parser utilities"
authors = []

[tool.poetry.dependencies]
python = "^3.7"
exifread = "*"
click = "*"
decorator = "*"
xmltodict = "*"
requests = "*"
pytz = "*"
timezonefinder = "^5.2.0"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-coverage= "*"
pre_commit = "*"
requests-mock = "*"

[tool.poetry.scripts]
imgparse = "imgparse.cli:cli"

[tool.poetry.extras]
dji_timestamps = ["timezonefinder"]

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["click", "decorator", "exifread", "pytest", "pytz", "requests", "timezonefinder", "xmltodict"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
