[project]
name = "imgparse"
version = "2.0.12"
description = "Python image-metadata-parser utilities"
authors = []
requires-python = ">=3.10,<4.0"
dependencies = [
    "exifread==3.1.0",
    "click",
    "xmltodict",
    "requests",
]

[project.optional-dependencies]
s3 = ["boto3", "s3path"]

[project.scripts]
imgparse = "imgparse.cli:cli"

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
    "pre-commit",
    "requests-mock",
    "mypy",
    "types-requests",
    "boto3-stubs[s3]",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
include = [{ path = "imgparse/py.typed", format = ["sdist", "wheel"] }]
