name: Checks

run-name: Testing ${{ github.ref_name }}
on: [push]
jobs:
  lint-typecheck-test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.6.1-0

      - name: Install Poetry
        uses: snok/install-poetry@bafa4d4adfc54e5fba0da6c1eb34001a4fdbaa4c # v1.0
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
    
      - name: Install Dependencies
        run: PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring poetry install --no-interaction --no-root -E timestamps
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - name: Install Project w/ Dev
        run: poetry install --no-interaction -E timestamps

      - name: Cache Pre-Commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-0|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      
      - name: Pre-Commit
        run: poetry run pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Tests
        run: poetry run pytest